name: Remote SSH Command
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd personal-website
            git pull origin main
            docker compose down || true
            docker image rm personal-website-nginx || true
            docker compose up -d --build